pipeline {
    agent { label 'dind-3' } // Especifica el agente en el que deseas ejecutar el pipeline
    environment {
        SERVER_URL = 'gamezssl.jfrog.io'
    }
    stages {
        stage('Complicacion/Build') {
            steps {
                script {
                    def server = Artifactory.server(SERVER_URL)
                    def rtGradle = Artifactory.newGradleBuild()
                    def buildInfo = Artifactory.newBuildInfo()
                    
                    git branch: 'main', url: 'https://github.com/gamezssl/gs-gradle.git'

                    rtGradle.tool = 'gradle-jenkins' // Nombre de la herramienta Gradle en Jenkins
                    rtGradle.deployer repo: 'default-gradle-dev-local', server: server
                    rtGradle.resolver repo: 'default-gradle-dev', server: server

                    buildInfo.env.capture = true
                    buildInfo.env.filter.addInclude("*")
                    
                    rtGradle.usesPlugin = true

                    rtGradle.run rootDir: "artifactory/", tasks: 'clean artifactoryPublish', buildInfo: buildInfo

                    server.publishBuildInfo buildInfo
                }
            }
        }
    }
}